<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modelos\Modelos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\ARXLibreria\ARXLibreria\bin\Debug\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\..\ARXLibreria\ARXLibreria\bin\Debug\NLog.dll</HintPath>
    </Reference>
    <Reference Include="PetaPoco">
      <HintPath>..\..\ARXLibreria\ARXLibreria\bin\Debug\PetaPoco.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
